<section id="screen-timer" class="screen">

    <div class="timer-display">
        <div class="stopwatch-display" id="stopwatch">00:00:00</div>
        <button id="reset" title="Reset">Reset</button>
    </div>

    <div class="results-section">
        <div class="results-header" id="results-header">
            <button id="export" title="Export Results">Export Results</button>
        </div>
        <div class="results-list-container" id="results-list">
        </div>
    </div>

    <footer class="timer-footer">
        <button id="startStop" title="Start/Stop">
            <img src="images/icons8-play-white.png" alt="Play" class="icon">
        </button>
        <button id="lap" title="Lap">
            <img src="images/icons8-stopwatch-white.png" alt="Play" class="icon">
        </button>
    </footer>
    
</section>